import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import BlogSiteShell from "@/components/BlogSiteShell";
import { publishedArticle } from "@/lib/blog";

export const dynamic = "force-dynamic";
type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const article = await publishedArticle((await params).slug); if (!article) return {}; const title = article.seo_title || article.title; const description = article.seo_description || article.excerpt || undefined; return { title, description, alternates: { canonical: `https://dobryvodar.sk/blog/${article.slug}` }, openGraph: { type: "article", title, description, url: `https://dobryvodar.sk/blog/${article.slug}` } }; }
export default async function ArticlePage({ params }: Props) { const article = await publishedArticle((await params).slug); if (!article) notFound(); const publishedAt = article.published_at || new Date().toISOString(); const url = `https://dobryvodar.sk/blog/${article.slug}`; const schema = { "@context": "https://schema.org", "@type": "Article", headline: article.title, datePublished: publishedAt, mainEntityOfPage: url, author: { "@type": "Organization", name: "Dobrý Vodár" } };
  return <BlogSiteShell><article className="mx-auto max-w-3xl px-5 py-10 sm:px-6 md:px-10 md:py-16"><Link href="/blog" className="text-sm font-semibold text-primary hover:underline">← Všetky články</Link><p className="mt-8 text-sm text-muted-foreground">{new Intl.DateTimeFormat("sk-SK", { dateStyle: "long" }).format(new Date(publishedAt))}</p><h1 className="mt-3 text-3xl font-bold leading-tight tracking-tight sm:text-4xl md:text-5xl">{article.title}</h1>{article.excerpt ? <p className="mt-5 text-lg leading-8 text-muted-foreground sm:mt-6 sm:text-xl">{article.excerpt}</p> : null}{article.cover_image_url ? <div className="relative mt-8 aspect-[16/9] w-full overflow-hidden rounded-2xl bg-secondary shadow-lg"><Image src={article.cover_image_url} alt={article.title} fill priority className="object-cover" sizes="(max-width: 767px) 100vw, 768px" /></div> : null}<div className="prose prose-slate mt-10 max-w-none text-[1.05rem] leading-8 prose-headings:font-bold prose-headings:tracking-tight prose-h2:mt-12 prose-h2:scroll-mt-28 prose-h2:text-2xl prose-h2:leading-tight sm:prose-h2:text-3xl prose-h3:mt-10 prose-h3:text-xl prose-h3:leading-tight sm:prose-h3:text-2xl prose-p:my-5 prose-p:leading-8 prose-a:font-semibold prose-a:text-primary prose-a:no-underline hover:prose-a:underline prose-ul:my-6 prose-ul:space-y-2 prose-ol:my-6 prose-ol:space-y-2 prose-li:my-1 prose-blockquote:border-primary prose-blockquote:font-medium prose-img:my-8 prose-img:w-full prose-img:rounded-2xl prose-img:shadow-lg prose-figure:my-8 prose-figcaption:text-center prose-figcaption:text-sm prose-figcaption:text-muted-foreground" dangerouslySetInnerHTML={{ __html: article.content_html }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /></article></BlogSiteShell>;
}
