import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { CalendarDays, Clock3 } from "lucide-react";
import { notFound } from "next/navigation";
import BlogSiteShell from "@/components/BlogSiteShell";
import { BLOG_FALLBACK_IMAGES, publishedArticle } from "@/lib/blog";

export const dynamic = "force-dynamic";
type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const article = await publishedArticle((await params).slug); if (!article) return {}; const title = article.seo_title || article.title; const description = article.seo_description || article.excerpt || undefined; return { title, description, alternates: { canonical: `https://dobryvodar.sk/blog/${article.slug}` }, openGraph: { type: "article", title, description, url: `https://dobryvodar.sk/blog/${article.slug}` } }; }
export default async function ArticlePage({ params }: Props) { const article = await publishedArticle((await params).slug); if (!article) notFound(); const publishedAt = article.published_at || new Date().toISOString(); const image = article.cover_image_url || BLOG_FALLBACK_IMAGES[article.id % BLOG_FALLBACK_IMAGES.length]; const url = `https://dobryvodar.sk/blog/${article.slug}`; const schema = { "@context": "https://schema.org", "@type": "Article", headline: article.title, datePublished: publishedAt, mainEntityOfPage: url, author: { "@type": "Organization", name: "Dobrý Vodár" } };
  return <BlogSiteShell><article className="mx-auto max-w-6xl px-5 py-10 sm:px-6 md:px-10 md:py-16"><div className="mx-auto max-w-5xl"><Link href="/blog" className="text-sm font-semibold text-primary hover:underline">← Všetky články</Link><div className="mt-8 max-w-4xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-primary">Praktické rady</p><h1 className="mt-3 text-3xl font-bold leading-tight tracking-tight sm:text-4xl md:text-6xl">{article.title}</h1>{article.excerpt ? <p className="mt-5 max-w-3xl text-lg leading-8 text-muted-foreground sm:mt-6 sm:text-xl">{article.excerpt}</p> : null}<div className="mt-6 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm font-medium text-muted-foreground"><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-primary" />{new Intl.DateTimeFormat("sk-SK", { dateStyle: "long" }).format(new Date(publishedAt))}</span><span className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-primary" />Čítanie: 4 min</span></div></div><div className="relative mt-8 aspect-[16/9] w-full overflow-hidden rounded-3xl bg-secondary shadow-xl"><Image src={image} alt={article.title} fill priority className="object-cover" sizes="(max-width: 1023px) 100vw, 1120px" /></div></div><div className="mx-auto mt-10 max-w-4xl rounded-3xl border border-border/80 bg-card px-5 py-7 shadow-[0_16px_38px_-28px_hsl(204_70%_35%_/_0.45)] sm:px-8 sm:py-10 md:px-12"><div className="prose prose-slate max-w-none text-base leading-8 prose-headings:font-bold prose-headings:tracking-tight prose-h2:mt-12 prose-h2:scroll-mt-28 prose-h2:border-l-4 prose-h2:border-primary prose-h2:pl-4 prose-h2:text-2xl prose-h2:leading-tight sm:prose-h2:text-3xl prose-h3:mt-10 prose-h3:text-xl prose-h3:leading-tight sm:prose-h3:text-2xl prose-p:my-7 prose-p:leading-8 prose-a:font-semibold prose-a:text-primary prose-a:no-underline hover:prose-a:underline prose-ul:my-7 prose-ul:space-y-3 prose-ul:marker:text-primary prose-ol:my-7 prose-ol:space-y-3 prose-ol:marker:font-bold prose-ol:marker:text-primary prose-li:pl-1 prose-blockquote:my-8 prose-blockquote:rounded-r-xl prose-blockquote:border-primary prose-blockquote:bg-secondary/60 prose-blockquote:px-5 prose-blockquote:py-4 prose-blockquote:font-medium prose-img:my-9 prose-img:w-full prose-img:rounded-2xl prose-img:shadow-lg prose-figure:my-9 prose-figcaption:text-center prose-figcaption:text-sm prose-figcaption:text-muted-foreground" dangerouslySetInnerHTML={{ __html: article.content_html }} /></div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /></article></BlogSiteShell>;
}
